name: Eric Stotts Architect
favicon: null
layout_spectrum: 0.2577
typography_spectrum: 0.51136
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050409'
    - '#fff9e9'
    - '#bda778'
    - '#938060'
    - '#253534'
  brandStrength: 0
  lightness: 0.8125
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
